[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "haxmasDay9_Allenay"
version = "0.0.1"
dependencies = [
    "textual",
]

[project.scripts]
advent-calendar = "haxmasDay9_Allenay.main:main"
